version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - ./app:/app/app
      - ${STORAGE_PATH:-./storage}:/app/storage
    environment:
      - API_KEY=${API_KEY:-51Nj8UxKGLqm7Xt9Aw3RzBvF8qY6cJpL2tMn7DkZxC9Hs5EoVfGjTy2Lm1Rk3Pb8N}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://user:password@postgres/scraper_db}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
      - TWILIO_TO_NUMBER=${TWILIO_TO_NUMBER}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_RECEIVER=${EMAIL_RECEIVER}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PORT=${PORT:-8000}
      - HOST=${HOST:-0.0.0.0}
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-scraper_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  storage:
  postgres_data:
